export const Data = [
  {
    breed: "Labrador Retriever",
    country: "Canada",
    furcolor: "Yellow, Black, Chocolate",
    height: "21-24",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Loyal, friendly, intelligent, energetic, good-natured",
    health: "Hip dysplasia, obesity, ear infections",
  },
  {
    breed: "German Shepherd",
    country: "Germany",
    furcolor: "Black, Tan",
    height: "22-26",
    eyecolor: "Brown",
    longevity: "7-10",
    character: "Loyal, intelligent, protective, confident, trainable",
    health: "Hip dysplasia, elbow dysplasia, pancreatitis",
  },
  {
    breed: "Bulldog",
    country: "England",
    furcolor: "White, Red",
    height: "12-16",
    eyecolor: "Brown",
    longevity: "8-10",
    character: "Loyal, calm, gentle, brave",
    health: "Skin allergies, respiratory issues, obesity",
  },
  {
    breed: "Poodle",
    country: "France",
    furcolor: "White, Black, Brown, Apricot",
    height: "10-15",
    eyecolor: "Brown, Blue",
    longevity: "12-15",
    character: "Intelligent, active, affectionate, hypoallergenic",
    health: "Hip dysplasia, epilepsy, bladder stones",
  },
  {
    breed: "Beagle",
    country: "England",
    furcolor: "White, Tan, Red, Lemon",
    height: "13-15",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Curious, friendly, energetic, good-natured",
    health: "Ear infections, hip dysplasia, epilepsy",
  },
  {
    breed: "Chihuahua",
    country: "Mexico",
    furcolor: "Black, Brown, Tan, White",
    height: "6-9",
    eyecolor: "Brown, Blue",
    longevity: "12-20",
    character: "Loyal, energetic, confident, sensitive",
    health: "Dental problems, eye issues, respiratory issues",
  },
  {
    breed: "Boxer",
    country: "Germany",
    furcolor: "Fawn, Brindle",
    height: "21-25",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Loyal, energetic, intelligent, playful, protective",
    health: "Hip dysplasia, cancer, heart conditions",
  },
  {
    breed: "Golden Retriever",
    country: "Scotland",
    furcolor: "Golden",
    height: "21-24",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Intelligent, friendly, kind, loyal, good-natured",
    health: "Hip dysplasia, cancer, skin allergies",
  },
  {
    breed: "Pug",
    country: "China",
    furcolor: "Fawn, Black",
    height: "10-14",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Loyal, playful, affectionate, social, charming",
    health: "Eye problems, respiratory issues, obesity",
  },
  {
    breed: "Rottweiler",
    country: "Germany",
    furcolor: "Black, Tan",
    height: "22-27",
    eyecolor: "Brown",
    longevity: "8-10",
    character: "Loyal, protective, confident, strong",
    health: "Hip dysplasia, cancer, elbow dysplasia",
  },
  {
    breed: "Siberian Husky",
    country: "Russia",
    furcolor: "Black, White",
    height: "21-24",
    eyecolor: "Blue",
    longevity: "12-15",
    character: "Independent, energetic, intelligent, playful, strong",
    health: "Hip dysplasia, eye problems, hereditary myopathy",
  },
  {
    breed: "Dachshund",
    country: "Germany",
    furcolor: "Black, Tan",
    height: "5-9",
    eyecolor: "Brown, Blue",
    longevity: "12-15",
    character: "Loyal, energetic, playful, curious",
    health: "Intervertebral disc disease, hip dysplasia, diabetes",
  },
  {
    breed: "Shih Tzu",
    country: "China",
    furcolor: "Black, White, Brown",
    height: "9-10",
    eyecolor: "Brown",
    longevity: "10-16",
    character: "Affectionate, playful, confident, good-natured",
    health: "Dental problems, respiratory issues, eye problems",
  },
  {
    breed: "Bichon Frise",
    country: "France",
    furcolor: "White",
    height: "9-11",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Playful, affectionate, intelligent, social",
    health: "Dental problems, eye problems, bladder stones",
  },
  {
    breed: "Australian Shepherd",
    country: "Australia",
    furcolor: "Black, Red",
    height: "18-23",
    eyecolor: "Brown, Blue",
    longevity: "12-15",
    character: "Intelligent, energetic, loyal, trainable",
    health: "Hip dysplasia, eye problems, epilepsy",
  },
  {
    breed: "Basset Hound",
    country: "France",
    furcolor: "Black, Tan",
    height: "11-15",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Affectionate, patient, gentle, good-natured",
    health: "Dental problems, ear infections, obesity",
  },
  {
    breed: "Cocker Spaniel",
    country: "England",
    furcolor: "Black, Brown",
    height: "14-15",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Affectionate, intelligent, energetic, good-natured",
    health: "Ear infections, hip dysplasia, eye problems",
  },
  {
    breed: "French Bulldog",
    country: "France",
    furcolor: "White, Black, Brindle",
    height: "11-12",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Affectionate, playful, good-natured",
    health: "Breathing problems, eye problems, hip dysplasia",
  },
  {
    breed: "Pomeranian",
    country: "Germany",
    furcolor: "Orange, Sable, Black",
    height: "6-7",
    eyecolor: "Brown",
    longevity: "12-16",
    character: "Playful, energetic, intelligent, good-natured",
    health: "Dental problems, eye problems, obesity",
  },
  {
    breed: "Great Dane",
    country: "Germany",
    furcolor: "Black, Blue, Fawn, Harlequin",
    height: "28-34",
    eyecolor: "Brown",
    longevity: "8-10",
    character: "Gentle, loyal, intelligent, good-natured",
    health: "Hip dysplasia, cancer, heart conditions",
  },
  {
    breed: "Mastiff",
    country: "England",
    furcolor: "Apricot, Fawn",
    height: "30-34",
    eyecolor: "Brown",
    longevity: "8-10",
    character: "Loyal, gentle, protective, good-natured",
    health: "Hip dysplasia, heart conditions, cancer",
  },
  {
    breed: "Newfoundland",
    country: "Canada",
    furcolor: "Black, Brown, Grey",
    height: "26-28",
    eyecolor: "Brown",
    longevity: "9-11",
    character: "Loyal, intelligent, gentle, good-natured",
    health: "Hip dysplasia, heart conditions, cancer",
  },
  {
    breed: "Saint Bernard",
    country: "Switzerland",
    furcolor: "Red, White",
    height: "26-30",
    eyecolor: "Brown",
    longevity: "8-10",
    character: "Loyal, intelligent, gentle, protective",
    health: "Hip dysplasia, cancer, heart conditions",
  },
  {
    breed: "Old English Sheepdog",
    country: "England",
    furcolor: "Blue, Grey",
    height: "22-26",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Gentle, intelligent, good-natured, protective",
    health: "Hip dysplasia, eye problems, skin allergies",
  },
  {
    breed: "Irish Wolfhound",
    country: "Ireland",
    furcolor: "Grey, Red, Black",
    height: "30-35",
    eyecolor: "Brown",
    longevity: "6-8",
    character: "Gentle, loyal, intelligent, good-natured",
    health: "Hip dysplasia, heart conditions, cancer",
  },
  {
    breed: "Greyhound",
    country: "England",
    furcolor: "Black, White, Brindle",
    height: "26-30",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Intelligent, athletic, sensitive, good-natured",
    health: "Hip dysplasia, eye problems, heart conditions",
  },
  {
    breed: "Scottish Deerhound",
    country: "Scotland",
    furcolor: "Blue, Grey",
    height: "28-32",
    eyecolor: "Brown",
    longevity: "8-10",
    character: "Gentle, intelligent, good-natured, independent",
    health: "Hip dysplasia, heart conditions, cancer",
  },
  {
    breed: "Great Pyrenees",
    country: "France",
    furcolor: "White",
    height: "25-32",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Loyal, intelligent, gentle, protective",
    health: "Hip dysplasia, cancer, skin allergies",
  },
  {
    breed: "Shar Pei",
    country: "China",
    furcolor: "Cream, Fawn",
    height: "18-20",
    eyecolor: "Brown",
    longevity: "8-12",
    character: "Independent, loyal, intelligent, good-natured",
    health: "Skin allergies, eye problems, hip dysplasia",
  },
  {
    breed: "Doberman Pinscher",
    country: "Germany",
    furcolor: "Black, Red",
    height: "24-28",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Loyal, energetic, intelligent, protective",
    health: "Hip dysplasia, heart conditions, cancer",
  },
  {
    breed: "Weimaraner",
    country: "Germany",
    furcolor: "Silver, Grey",
    height: "25-29",
    eyecolor: "Blue, Grey",
    longevity: "10-12",
    character: "Energetic, intelligent, good-natured, loyal",
    health: "Hip dysplasia, eye problems, cancer",
  },
  {
    breed: "Belgian Malinois",
    country: "Belgium",
    furcolor: "Fawn, Mahogany",
    height: "22-26",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, loyal, protective",
    health: "Hip dysplasia, eye problems, skin allergies",
  },
  {
    breed: "Rhodesian Ridgeback",
    country: "Rhodesia",
    furcolor: "Light Wheaten",
    height: "25-27",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Intelligent, athletic, loyal, good-natured",
    health: "Hip dysplasia, eye problems, cancer",
  },
  {
    breed: "English Setter",
    country: "England",
    furcolor: "Black, White, Liver",
    height: "23-27",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, affectionate, good-natured",
    health: "Hip dysplasia, eye problems, cancer",
  },
  {
    breed: "Pointer",
    country: "England",
    furcolor: "Black, White, Liver",
    height: "21-27",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, good-natured, affectionate",
    health: "Hip dysplasia, eye problems, cancer",
  },
  {
    breed: "Gordon Setter",
    country: "Scotland",
    furcolor: "Black, Tan",
    height: "23-27",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, good-natured, affectionate",
    health: "Hip dysplasia, eye problems, cancer",
  },
  {
    breed: "Irish Setter",
    country: "Ireland",
    furcolor: "Red",
    height: "24-28",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, good-natured, affectionate",
    health: "Hip dysplasia, eye problems, cancer",
  },
  {
    breed: "Papillon",
    country: "France",
    furcolor: "White, Black, Sable, Red",
    height: "8-11",
    eyecolor: "Brown",
    longevity: "14-16",
    character: "Intelligent, energetic, affectionate, good-natured",
    health: "Dental problems, eye problems, bladder stones",
  },
  {
    breed: "Pekingese",
    country: "China",
    furcolor: "Black, White, Red",
    height: "6-9",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Independent, intelligent, affectionate, good-natured",
    health: "Dental problems, respiratory issues, eye problems",
  },
  {
    breed: "Toy Poodle",
    country: "France",
    furcolor: "White, Black, Brown, Apricot",
    height: "10-11",
    eyecolor: "Brown, Blue",
    longevity: "12-15",
    character: "Intelligent, active, affectionate, hypoallergenic",
    health: "Hip dysplasia, epilepsy, bladder stones",
  },
  {
    breed: "Miniature Poodle",
    country: "France",
    furcolor: "White, Black, Brown, Apricot",
    height: "10-15",
    eyecolor: "Brown, Blue",
    longevity: "12-15",
    character: "Intelligent, active, affectionate, hypoallergenic",
    health: "Hip dysplasia, epilepsy, bladder stones",
  },
  {
    breed: "Standard Poodle",
    country: "France",
    furcolor: "White, Black, Brown, Apricot",
    height: "15-22",
    eyecolor: "Brown, Blue",
    longevity: "12-15",
    character: "Intelligent, active, affectionate, hypoallergenic",
    health: "Hip dysplasia, epilepsy, bladder stones",
  },
  {
    breed: "Affenpinscher",
    country: "Germany",
    furcolor: "Black, Brown, Red",
    height: "9-11",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye problems, skin allergies",
  },
  {
    breed: "Boston Terrier",
    country: "United States",
    furcolor: "Black, White",
    height: "15-17",
    eyecolor: "Brown",
    longevity: "11-13",
    character: "Intelligent, energetic, affectionate, good-natured",
    health: "Eye problems, respiratory issues, skin allergies",
  },
  {
    breed: "Brussels Griffon",
    country: "Belgium",
    furcolor: "Black, Red",
    height: "7-10",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, affectionate, good-natured",
    health: "Dental problems, eye problems, respiratory issues",
  },
  {
    breed: "Cairn Terrier",
    country: "Scotland",
    furcolor: "Black, Wheaten, Red",
    height: "10-12",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye problems, skin allergies",
  },
  {
    breed: "Chinese Crested",
    country: "China",
    furcolor: "Pink, White, Black",
    height: "11-13",
    eyecolor: "Brown",
    longevity: "13-18",
    character: "Intelligent, energetic, affectionate, good-natured",
    health: "Dental problems, eye problems, skin allergies",
  },
  {
    breed: "Miniature Schnauzer",
    country: "Germany",
    furcolor: "Black, Salt & Pepper, White",
    height: "12-14",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, pancreatitis, diabetes",
  },
  {
    breed: "Standard Schnauzer",
    country: "Germany",
    furcolor: "Black, Salt & Pepper",
    height: "18-20",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, pancreatitis, diabetes",
  },
  {
    breed: "West Highland White Terrier",
    country: "Scotland",
    furcolor: "White",
    height: "11-12",
    eyecolor: "Brown",
    longevity: "12-16",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, skin allergies, hip dysplasia",
  },
  {
    breed: "Australian Terrier",
    country: "Australia",
    furcolor: "Red, Black & Tan",
    height: "10-11",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, skin allergies, hip dysplasia",
  },
  {
    breed: "Border Terrier",
    country: "England",
    furcolor: "Red, Wheaten, Black",
    height: "10-16",
    eyecolor: "Brown",
    longevity: "12-16",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, skin allergies, hip dysplasia",
  },
  {
    breed: "Coton de Tulear",
    country: "Madagascar",
    furcolor: "White",
    height: "9-11",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, skin allergies, hip dysplasia",
  },
  {
    breed: "English Toy Spaniel",
    country: "England",
    furcolor: "White, Blenheim",
    height: "10-12",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, skin allergies, hip dysplasia",
  },
  {
    breed: "Australian Stumpy Tail Cattle Dog",
    country: "Australia",
    furcolor: "Red, Black",
    height: "17-20",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, good-natured, loyal",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Pug",
    country: "China",
    furcolor: "Black, Fawn",
    height: "10-14",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, respiratory issues, eye problems",
  },
  {
    breed: "American Eskimo Dog",
    country: "United States",
    furcolor: "White",
    height: "15-19",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, skin allergies, hip dysplasia",
  },
  {
    breed: "Australian Cattle Dog",
    country: "Australia",
    furcolor: "Blue, Red",
    height: "17-20",
    eyecolor: "Brown",
    longevity: "12-16",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, skin allergies, hip dysplasia",
  },
  {
    breed: "Basset Hound",
    country: "France",
    furcolor: "Black, White, Red",
    height: "11-15",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Gentle, good-natured, loyal, intelligent",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Australian Kelpie",
    country: "Australia",
    furcolor: "Red, Black",
    height: "17-20",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, good-natured, loyal",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Bloodhound",
    country: "England",
    furcolor: "Red, Black",
    height: "22-27",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Loyal, intelligent, good-natured, energetic",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Border Collie",
    country: "England",
    furcolor: "Black, White, Red",
    height: "18-22",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Australian Shepherd",
    country: "Australia",
    furcolor: "Blue Merle",
    height: "20-23",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, good-natured, loyal",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "American Bulldog",
    country: "United States",
    furcolor: "White, Red",
    height: "20-28",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Loyal, intelligent, good-natured, energetic",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Australian Shepherd",
    country: "Australia",
    furcolor: "Black, Red",
    height: "18-23",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, skin allergies, hip dysplasia",
  },
  {
    breed: "Borzoi",
    country: "Russia",
    furcolor: "White, Cream, Red",
    height: "26-29",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Gentle, good-natured, loyal, intelligent",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Bull Terrier",
    country: "England",
    furcolor: "White, Red",
    height: "20-22",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Loyal, intelligent, good-natured, energetic",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Cane Corso",
    country: "Italy",
    furcolor: "Black, Red",
    height: "22-28",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Loyal, intelligent, good-natured, energetic",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Cardigan Welsh Corgi",
    country: "Wales",
    furcolor: "Red, Sable, Black",
    height: "10-12",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Chesapeake Bay Retriever",
    country: "United States",
    furcolor: "Brown, Tan",
    height: "21-26",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Saluki",
    country: "Middle East",
    furcolor: "Cream, Red",
    height: "23-28",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, good-natured, loyal",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "English Setter",
    country: "England",
    furcolor: "Liver, Blue",
    height: "25-27",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "English Springer Spaniel",
    country: "England",
    furcolor: "Black, White, Liver",
    height: "20-24",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Field Spaniel",
    country: "England",
    furcolor: "Black, Liver",
    height: "15-18",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Finnish Spitz",
    country: "Finland",
    furcolor: "Red, Golden",
    height: "15-20",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Flat-Coated Retriever",
    country: "England",
    furcolor: "Black, Liver",
    height: "22-25",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Australian Terrier",
    country: "Australia",
    furcolor: "Red",
    height: "10-11",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Giant Schnauzer",
    country: "Germany",
    furcolor: "Black, Salt & Pepper",
    height: "25-28",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Loyal, intelligent, good-natured, energetic",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Golden Retriever",
    country: "Scotland",
    furcolor: "Gold",
    height: "21-24",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Gordon Setter",
    country: "Scotland",
    furcolor: "Black, Tan",
    height: "24-27",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Australian Cattle Dog",
    country: "Australia",
    furcolor: "Blue, Red",
    height: "17-20",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, good-natured, loyal",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Greyhound",
    country: "England",
    furcolor: "White, Black, Red",
    height: "26-30",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Intelligent, energetic, good-natured, loyal",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Harrier",
    country: "England",
    furcolor: "Red, Black & Tan",
    height: "18-21",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Irish Setter",
    country: "Ireland",
    furcolor: "Red",
    height: "26-28",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Irish Terrier",
    country: "Ireland",
    furcolor: "Red",
    height: "14-16",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Irish Water Spaniel",
    country: "Ireland",
    furcolor: "Brown",
    height: "21-24",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Irish Wolfhound",
    country: "Ireland",
    furcolor: "Grey, Red",
    height: "30-35",
    eyecolor: "Brown",
    longevity: "6-10",
    character: "Loyal, intelligent, good-natured, energetic",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Italian Greyhound",
    country: "Italy",
    furcolor: "Red, Black",
    height: "13-15",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Jack Russell Terrier",
    country: "England",
    furcolor: "White, Black & Tan",
    height: "10-12",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Japanese Chin",
    country: "Japan",
    furcolor: "Black, Red",
    height: "7-11",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Keeshond",
    country: "Netherlands",
    furcolor: "Black, Cream",
    height: "17-19",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Kerry Blue Terrier",
    country: "Ireland",
    furcolor: "Blue",
    height: "17-19",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Kuvasz",
    country: "Hungary",
    furcolor: "White",
    height: "25-29",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Loyal, intelligent, good-natured, energetic",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Lhasa Apso",
    country: "Tibet",
    furcolor: "Black, White",
    height: "10-11",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Maltese",
    country: "Malta",
    furcolor: "White",
    height: "8-10",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Miniature Pinscher",
    country: "Germany",
    furcolor: "Red, Stag Red",
    height: "10-12",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Samoyed",
    country: "Russia",
    furcolor: "White",
    height: "21-23",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Shetland Sheepdog",
    country: "Scotland",
    furcolor: "Sable, Black",
    height: "13-16",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Staffordshire Bull Terrier",
    country: "England",
    furcolor: "White, Black, Red",
    height: "14-16",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Vizsla",
    country: "Hungary",
    furcolor: "Red",
    height: "20-24",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Anatolian Shepherd",
    country: "Turkey",
    furcolor: "Fawn",
    height: "27-29",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Loyal, intelligent, good-natured, energetic",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Welsh Corgi",
    country: "Wales",
    furcolor: "Red, Sable",
    height: "10-12",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Welsh Springer Spaniel",
    country: "Wales",
    furcolor: "Liver, White",
    height: "20-25",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Welsh Terrier",
    country: "Wales",
    furcolor: "Black, Tan",
    height: "10-12",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "West Highland White Terrier",
    country: "Scotland",
    furcolor: "White",
    height: "10-12",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Whippet",
    country: "England",
    furcolor: "White, Black, Red",
    height: "18-22",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, good-natured, loyal",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Wirehaired Pointing Griffon",
    country: "Belgium",
    furcolor: "Brown, White",
    height: "21-24",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Xoloitzcuintli",
    country: "Mexico",
    furcolor: "Black, Red",
    height: "10-14",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Yorkshire Terrier",
    country: "England",
    furcolor: "Blue & Tan",
    height: "7-8",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Akita",
    country: "Japan",
    furcolor: "Red, Fawn, Sesame",
    height: "24-28",
    eyecolor: "Brown",
    longevity: "10-12",
    character: "Loyal, intelligent, good-natured, energetic",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Africanis",
    country: "Africa",
    furcolor: "Brown, Red",
    height: "22-25",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, good-natured, loyal",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Basenji",
    country: "Congo",
    furcolor: "Red, Black & White",
    height: "16-17",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Catahoula Leopard Dog",
    country: "United States",
    furcolor: "Merle, Black",
    height: "20-26",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, good-natured, loyal",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Cocker Spaniel",
    country: "England",
    furcolor: "Black, Brown",
    height: "14-15",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Miniature Shiba Inu",
    country: "Japan",
    furcolor: "Red, Sesame",
    height: "13-16",
    eyecolor: "Brown",
    longevity: "12-15",
    character: "Intelligent, energetic, playful, good-natured",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Belgian Tervuren",
    country: "Belgium",
    furcolor: "Fawn",
    height: "22-26",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, good-natured, loyal",
    health: "Dental problems, eye issues, skin allergies",
  },
  {
    breed: "Pharaoh Hound",
    country: "Malta",
    furcolor: "Red",
    height: "21-25",
    eyecolor: "Brown",
    longevity: "12-14",
    character: "Intelligent, energetic, good-natured, loyal",
    health: "Dental problems, eye issues, skin allergies",
  },
];
